name: timetable_example
description: A simple example app for the timetable package
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.3.0'

dependencies:
  debug_overlay: ^0.2.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  timetable:
    path: ../

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
