name: timetable_example
description: A simple example app for the timetable package
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  debug_overlay: ^0.1.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  timetable:
    path: ../

flutter:
  uses-material-design: true
