name: timetable
description: Customizable, animated calendar widget including day, week, and month views
version: 1.0.0-alpha.13
repository: https://github.com/JonasWanke/timetable
screenshots:
  - description: Navigation with synchronized month and week views
    path: doc/demo-navigation.webp
  - description: Default date and time animations
    path: doc/demo-animation.webp
  - description: Many different callbacks
    path: doc/demo-callbacks.webp
  - description: Changeable `VisibleDateRange`
    path: doc/demo-visibleDateRange.webp
  - description: Support for dark mode
    path: doc/screenshot-MultiDateTimetable-dark.webp
  - description: Support for drag and drop
    path: doc/demo-dragAndDrop.webp

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  async: ^2.6.0
  black_hole_flutter: ^1.0.0
  collection: ^1.15.0
  dart_date: ^1.1.0
  dartx: ^1.0.0
  flutter:
    sdk: flutter
  flutter_layout_grid: ^2.0.0
  intl: ">=0.17.0 <0.20.0"
  meta: ^1.3.0

dev_dependencies:
  dart_code_metrics: ^5.0.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  glados: ^1.0.0
  test: ^1.9.4
