name: timetable
description: 'ğŸ“… Customizable, animated calendar widget including day, week, and month views'
version: 1.0.0-alpha.6
homepage: https://github.com/JonasWanke/timetable

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.8.0'

dependencies:
  async: ^2.6.0
  black_hole_flutter: ^0.3.0
  collection: ^1.15.0
  dart_date: ^1.1.0
  flutter:
    sdk: flutter
  flutter_layout_grid: ^1.0.1
  intl: ^0.17.0
  meta: ^1.3.0
  supercharged: ^2.0.0
  tuple: ^2.0.0

dev_dependencies:
  extra_pedantic: ^1.3.0
  flutter_test:
    sdk: flutter
  glados: ^1.0.0
  test: ^1.9.4
  tuple_glados: ^1.0.0
